import { COURSE_ALLOCATION } from './order.const';

export enum COURSE_TYPE {
  MOVING = 0,
  GENERAL,
}

export enum LINK_TO_SSCV {
  NOT_LINKED = 0,
  LINK,
}

export enum COURSE_STATUS {
  INCOMPLETE = 0,
  COMPLETE,
  DELETE,
}

export const courseInfo = [
  {
    id: '01',
    title: '東大阪支店',
    loadingTime: '08:20',
    unLoadingTime: '9:30',
    loading: 1,
    unLoading: 3,
    courses: [
      {
        id: '000000001',
        name: '森本正和',
      },
    ],
  },
  {
    id: '02',
    title: '御手島ターミナル',
    loadingTime: '08:20',
    unLoadingTime: '9:30',
    loading: 3,
    unLoading: 0,
    courses: [
      {
        id: '000000001',
        name: '森本正和',
      },
      {
        id: '000000003',
        name: '西口巴菜',
      },
      {
        id: '000000005',
        name: '田淵ゆ...',
      },
    ],
  },
  {
    id: '03',
    title: '新東京ターミナル',
    loadingTime: '-',
    unLoadingTime: '16:30',
    loading: 0,
    unLoading: 2,
    courses: [
      {
        id: '000000001',
        name: '森本正和',
      },
      {
        id: '000000003',
        name: '西口巴菜',
      },
    ],
  },
  {
    id: '04',
    title: '北大阪支店',
    loadingTime: '-',
    unLoadingTime: '-',
    loading: 1,
    unLoading: 0,
    courses: [
      {
        id: '000000001',
        name: '森本正和',
      },
      {
        id: '000000002',
        name: '西口巴菜',
      },
    ],
  },
  {
    id: '05',
    title: '北大阪支店',
    loadingTime: '-',
    unLoadingTime: '-',
    loading: 1,
    unLoading: 0,
    courses: [
      {
        id: '000000001',
        name: '森本正和',
      },
      {
        id: '000000002',
        name: '西口巴菜',
      },
    ],
  },
  {
    id: '06',
    title: '北大阪支店',
    loadingTime: '-',
    unLoadingTime: '-',
    loading: 1,
    unLoading: 0,
    courses: [
      {
        id: '000000001',
        name: '森本正和',
      },
      {
        id: '000000002',
        name: '西口巴菜',
      },
    ],
  },
  {
    id: '07',
    title: '北大阪支店',
    loadingTime: '-',
    unLoadingTime: '-',
    loading: 1,
    unLoading: 0,
    courses: [
      {
        id: '000000001',
        name: '森本正和',
      },
      {
        id: '000000002',
        name: '西口巴菜',
      },
    ],
  },
  {
    id: '08',
    title: '北大阪支店',
    loadingTime: '-',
    unLoadingTime: '-',
    loading: 1,
    unLoading: 0,
    courses: [
      {
        id: '000000001',
        name: '森本正和',
      },
      {
        id: '000000002',
        name: '西口巴菜',
      },
    ],
  },
  {
    id: '09',
    title: '北大阪支店',
    loadingTime: '-',
    unLoadingTime: '-',
    loading: 1,
    unLoading: 0,
    courses: [
      {
        id: '000000001',
        name: '森本正和',
      },
      {
        id: '000000002',
        name: '西口巴菜',
      },
    ],
  },
];

export const courses = [
  {
    order: '0000000001',
    groupId: '0307001',
    type: COURSE_TYPE.GENERAL,
    loadingDate: '23/08/25 (金)',
    loadingTime: '-',
    unloadingDate: '23/08/20 (日)',
    unloadingTime: '10:20',
    unloadingDestPrefecture: '近畿',
    unloadingDestCity: '京都府',
    desiredVehicle: '4t',
    packaging: '-',
    quantity: '10',
    cubicMeter: '20',
    loadingNotes: '23/08/23 12:00まで ',
    unloadingNotes: '23/08/29 10:00まで',
    loadingConsolidatedStore: '佐世保市',
    unloadingConsolidatedStore: '12:00',
    loadingDestConference: 7,
    unloadingShop: 'アート京都北支店',
    totalSales: '50,000',
    remarks: '大阪集約センター',
  },
  {
    order: '0000000002',
    groupId: '0307001',
    type: COURSE_TYPE.MOVING,
    loadingDate: '23/08/25 (金)',
    loadingTime: '-',
    unloadingDate: '23/08/20 (日)',
    unloadingTime: '00:20',
    unloadingDestPrefecture: '近畿',
    unloadingDestCity: '京都府',
    desiredVehicle: '4t',
    packaging: '-',
    quantity: '10',
    cubicMeter: '20',
    loadingNotes: '23/08/23 12:00まで ',
    unloadingNotes: '23/08/29 10:00まで',
    loadingConsolidatedStore: '佐世保市',
    unloadingConsolidatedStore: '12:00',
    loadingDestConference: 7,
    unloadingShop: 'アート京都北支店',
    totalSales: '10,000',
    remarks: '大阪集約センター',
  },
  {
    order: '0000000003',
    groupId: '0307001',
    type: COURSE_TYPE.GENERAL,
    loadingDate: '23/08/25 (金)',
    loadingTime: '-',
    unloadingDate: '23/08/20 (日)',
    unloadingTime: '05:20',
    unloadingDestPrefecture: '近畿',
    unloadingDestCity: '京都府',
    desiredVehicle: '4t',
    packaging: '-',
    quantity: '10',
    cubicMeter: '20',
    loadingNotes: '23/08/23 12:00まで ',
    unloadingNotes: '23/08/29 10:00まで',
    loadingConsolidatedStore: '佐世保市',
    unloadingConsolidatedStore: '12:00',
    loadingDestConference: 7,
    unloadingShop: 'アート京都北支店',
    totalSales: '5,000',
    remarks: '大阪集約センター',
  },
  {
    order: '0000000004',
    groupId: '0307001',
    type: COURSE_TYPE.MOVING,
    loadingDate: '23/08/25 (金)',
    loadingTime: '-',
    unloadingDate: '23/08/20 (日)',
    unloadingTime: '10:20',
    unloadingDestPrefecture: '近畿',
    unloadingDestCity: '京都府',
    desiredVehicle: '4t',
    packaging: '-',
    quantity: '10',
    cubicMeter: '20',
    loadingNotes: '23/08/23 12:00まで ',
    unloadingNotes: '23/08/29 10:00まで',
    loadingConsolidatedStore: '佐世保市',
    unloadingConsolidatedStore: '12:00',
    loadingDestConference: 7,
    unloadingShop: 'アート京都北支店',
    totalSales: '1,000',
    remarks: '大阪集約センター',
  },
];

export const detailCourseMoving = [
  {
    orderId: '0000000001',
    status: COURSE_ALLOCATION.NOT_ASSIGNED,
    regularName: '森本正和',
    cubic: 20,
    loadingConsolidationStore: '東大阪支店',
    loadingDestConference: 'アート京都北支店',
    loadingDate: '23/08/29 (火)',
    loadingAppointmentTime: '8:20',
    loadingNotes: '',
    DestinationPrefecture: '',
    DestinationCity: 'アート東京北支店',
    unloadingConsolidationStore: '千葉支店',
    unloadingShop: '23/08/30 (水)',
    unloadingDate: 'DWJ3尼崎LDS',
    unloadingNotes: 'DWJ3尼崎LDS',
    unloadingAppointmentTime: '10:00',
    unloadingDestPrefecture: 'DWJ3尼崎LDS',
    unloadingDestCity: '板橋区',
  },
  {
    orderId: '0000000002',
    status: COURSE_ALLOCATION.NOT_ASSIGNED,
    regularName: '森本正和',
    cubic: 5,
    loadingConsolidationStore: '東大阪支店',
    loadingDestConference: 'アート京都北支店',
    loadingDate: '23/08/29 (火)',
    loadingAppointmentTime: '8:20',
    loadingNotes: '',
    DestinationPrefecture: '',
    DestinationCity: 'アート東京北支店',
    unloadingConsolidationStore: '-',
    unloadingShop: '23/08/30 (水)',
    unloadingDate: 'DWJ3尼崎LDS',
    unloadingNotes: 'DWJ3尼崎LDS',
    unloadingAppointmentTime: '14:00',
    unloadingDestPrefecture: 'DWJ3尼崎LDS',
    unloadingDestCity: '板橋区',
  },
  {
    orderId: '0000000003',
    status: COURSE_ALLOCATION.CONFIRMED,
    regularName: '森本正和',
    cubic: 10,
    loadingConsolidationStore: '東大阪支店',
    loadingDestConference: 'アート京都北支店',
    loadingDate: '23/08/29 (火)',
    loadingAppointmentTime: '8:20',
    loadingNotes: '',
    DestinationPrefecture: '',
    DestinationCity: 'アート東京北支店',
    unloadingConsolidationStore: '-',
    unloadingShop: '23/08/30 (水)',
    unloadingDate: 'DWJ3尼崎LDS',
    unloadingNotes: 'DWJ3尼崎LDS',
    unloadingAppointmentTime: '',
    unloadingDestPrefecture: 'DWJ3尼崎LDS',
    unloadingDestCity: '板橋区',
  },
  {
    orderId: '0000000004',
    status: COURSE_ALLOCATION.NOT_ASSIGNED,
    regularName: '森本正和',
    cubic: 6,
    loadingConsolidationStore: '東大阪支店',
    loadingDestConference: 'アート京都北支店',
    loadingDate: '23/08/29 (火)',
    loadingAppointmentTime: '8:20',
    loadingNotes: '',
    DestinationPrefecture: '',
    DestinationCity: 'アート東京北支店',
    unloadingConsolidationStore: '新東京ターミナル 京ター',
    unloadingShop: '23/08/30 (水)',
    unloadingDate: 'DWJ3尼崎LDS',
    unloadingNotes: 'DWJ3尼崎LDS',
    unloadingAppointmentTime: '15:00',
    unloadingDestPrefecture: 'DWJ3尼崎LDS',
    unloadingDestCity: '板橋区',
  },
];

export const detailCourseLogistic = [
  {
    orderId: '0000000001',
    status: COURSE_ALLOCATION.NOT_ASSIGNED,
    generalName: 'カゴ',
    packaging: 'カゴ',
    quantity: '10',
    loadingDate: '23/08/29 (火)',
    loadingTime: '8:20',
    destinationName: 'DWJ3尼崎LDS',
    DestinationPrefecture: '京都府',
    DestinationCity: '長岡京市',
    unloadingDate: '23/08/29 (火)',
    unloadingDestName: 'OOO3東淀川XPT',
    unloadingDestPrefecture: '京都府',
    unloadingDestCity: '京都府',
    unloadingTime: '20:00',
  },
  {
    orderId: '0000000002',
    status: COURSE_ALLOCATION.NOT_ASSIGNED,
    generalName: 'カゴ',
    packaging: 'カゴ',
    quantity: '5',
    loadingDate: '07/08/29 (火)',
    loadingTime: '8:20',
    destinationName: 'DWLDS',
    DestinationPrefecture: '京都府',
    DestinationCity: '長岡京市',
    unloadingDate: '23/08/29 (火)',
    unloadingDestName: 'O3淀川XPT',
    unloadingDestPrefecture: '京都府',
    unloadingDestCity: '京都府',
    unloadingTime: '20:00',
  },
];

export const detailCourseMixed = [
  {
    orderId: '0000000001',
    status: COURSE_ALLOCATION.NOT_ASSIGNED,
    regularName: '森本正和',
    generalName: 'センコー千葉PD',
    cubic: '10',
    packaging: 'カゴ',
    quantity: '10',
    loadingConsolidationStore: '東大阪支店',
    loadingDestConference: 'アート京都北支店',
    destinationName: 'DWJ3尼崎LDS',
    loadingDate: '23/08/29 (火)',
    loadingAppointmentTime: '10:00',
    loadingNotes: '23/08/29 12:00まで ',
    destinationPrefecture: '京都府',
    destinationCity: '長岡京市',
    unloadingConsolidationStore: '千葉支店千葉支店',
    unloadingShop: 'アート東京北支店',
    unloadingDestName: '新東京ターミナ京ターミナ',
    unloadingDate: '23/08/30 (水)',
    unloadingNotes: '23/08/30 12:00まで ででまま',
    unloadingAppointmentTime: '10:00',
    unloadingDestPrefecture: '東京都',
    unloadingDestCity: '板橋区',
    loadingTime: '8:20',
    unloadingTime: '20:00',
  },
  {
    orderId: '0000000002',
    status: COURSE_ALLOCATION.NOT_ASSIGNED,
    regularName: '森本正和',
    generalName: 'センコー千葉PD',
    cubic: '-',
    packaging: 'カゴ',
    quantity: '5',
    loadingConsolidationStore: '御手島ターミ御手島御手島',
    loadingDestConference: 'アート京都北支店',
    destinationName: '-',
    loadingDate: '23/08/29 (火)',
    loadingAppointmentTime: '-',
    loadingNotes: '23/08/29 12:00まで ',
    destinationPrefecture: '京都府',
    destinationCity: '界市',
    unloadingConsolidationStore: '千葉支店千葉支店',
    unloadingShop: 'アート東京北支店',
    unloadingDestName: '新東京ターミナ京ターミナ',
    unloadingDate: '23/08/30 (水)',
    unloadingNotes: '23/08/30 12:00まで ででまま',
    unloadingAppointmentTime: '-',
    unloadingDestPrefecture: '東京都',
    unloadingDestCity: '板橋区',
    loadingTime: '-',
    unloadingTime: '-',
  },
  {
    orderId: '0000000003',
    status: COURSE_ALLOCATION.CONFIRMED,
    regularName: '森本正和',
    generalName: '-',
    cubic: '10',
    packaging: '-',
    quantity: '10',
    loadingConsolidationStore: '-',
    loadingDestConference: 'アート京-都北支店',
    destinationName: '-',
    loadingDate: '23/08/29 (火)',
    loadingAppointmentTime: '-',
    loadingNotes: '23/08/29 12:00まで ',
    destinationPrefecture: '京都府',
    destinationCity: '長岡京市',
    unloadingConsolidationStore: '千葉支店千葉支店',
    unloadingShop: 'アート東京北支店',
    unloadingDestName: '新東京ターミナ京ターミナ',
    unloadingDate: '23/08/30 (水)',
    unloadingNotes: '23/08/30 12:00まで ででまま',
    unloadingAppointmentTime: '10:00',
    unloadingDestPrefecture: '東京都',
    unloadingDestCity: '板橋区',
    loadingTime: '-',
    unloadingTime: '-',
  },
];

export const courseList = [
  {
    groupId: '0307001',
    type: COURSE_TYPE.MOVING,
    status: COURSE_STATUS.COMPLETE,
    sscvLink: LINK_TO_SSCV.LINK,
    loadingDate: '23/08/20 (木)',
    firstLoadingTime: '10:02',
    unloadingDate: '23/08/20 (木)',
    firstUnloadingTime: '0:20',
    departurePlaceArea: '近畿',
    departurePlacePrefecture: '京都府',
    departurePlaceCity: '長岡京市',
    landingArea: '九州',
    landingPrefecture: '長崎県',
    destinationCity: '佐世保市',
    orderQuantity: '3',
    quantity: '10',
    cubic: '30',
    desiredVehicleSize: '30t',
    desiredVehicleClass: '平',
    vehicleSize: 'ウイング',
    carNumber: '4tウイング',
    requestBy: '大阪運送',
    actualCompany: '山田運送',
    driver: '田中 貴ー',
    totalFarePaid: '55,000',
    paymentFare: '50,000',
    expresswayFee: '5,000',
    remarks: '11:00ごろ作業完了予定。',
    courseId: '05100000007',
    branchInChange: '大阪支店',
  },
  {
    groupId: '0307003',
    type: COURSE_TYPE.GENERAL,
    status: COURSE_STATUS.DELETE,
    sscvLink: LINK_TO_SSCV.LINK,
    loadingDate: '23/08/20 (木)',
    firstLoadingTime: '8:12',
    unloadingDate: '23/08/20 (木)',
    firstUnloadingTime: '0:20',
    departurePlaceArea: '近畿',
    departurePlacePrefecture: '京都府',
    departurePlaceCity: '長岡京市',
    landingArea: '九州',
    landingPrefecture: '長崎県',
    destinationCity: '佐世保市',
    orderQuantity: '56',
    quantity: '4',
    cubic: '18',
    desiredVehicleSize: '11t',
    desiredVehicleClass: 'ゲート(跳ね上げ',
    vehicleSize: 'ウイング',
    carNumber: '4tウイング',
    requestBy: '大阪運送',
    actualCompany: '山田運送',
    driver: '田中 貴ー',
    totalFarePaid: '55,000',
    paymentFare: '50,000',
    expresswayFee: '5,000',
    remarks: '配達時間早めに。',
    courseId: '05100000006',
    branchInChange: '大阪支店',
  },
  {
    groupId: '0307010',
    type: COURSE_TYPE.MOVING,
    status: COURSE_STATUS.INCOMPLETE,
    sscvLink: LINK_TO_SSCV.NOT_LINKED,
    loadingDate: '23/08/20 (木)',
    firstLoadingTime: '10:02',
    unloadingDate: '23/08/20 (木)',
    firstUnloadingTime: '0:20',
    departurePlaceArea: '近畿',
    departurePlacePrefecture: '京都府',
    departurePlaceCity: '長岡京市',
    landingArea: '九州',
    landingPrefecture: '長崎県',
    destinationCity: '佐世保市',
    orderQuantity: '23',
    quantity: '5',
    cubic: '',
    desiredVehicleSize: '18t',
    desiredVehicleClass: 'ウイング',
    vehicleSize: 'ウイング',
    carNumber: '4tウイング',
    requestBy: '大阪運送',
    actualCompany: '山田運送',
    driver: '田中 貴ー',
    totalFarePaid: '1,000',
    paymentFare: '520,000',
    expresswayFee: '15,000',
    remarks: '11:00ごろ作予定。',
    courseId: '05100000011',
    branchInChange: '大阪支店',
  },
];

export const linkHref: LinkHref[] = [
  {
    text: '基本情報',
    link: 'basic_information',
  },
  {
    text: 'コース情報',
    link: 'course_information',
  },
  {
    text: '受注情報',
    link: 'order_information',
  },
  {
    text: '金額情報',
    link: 'amount_information',
  },
];
